### ISSUE TITLE
mantissa can be negative in float extended reduce?

### ISSUE THREAD

**Issue by claudeha** [jackyarndley/rust-fractal#28]
https://github.com/jackyarndley/rust-fractal/blob/4d5335991f06f5a49d52e97d5153e6339eef33b1/src/util/float_extended.rs#L26

I think the only time it is not safe to use frexp is for special values like 0, inf, nan. Though the range check may be a small optimization, if it took negative mantissa into account?

**Comment by jackyarndley** [comment]
Thanks for the issue. This definitely is an error on my part, however I believe it did not make a difference in the program. The floatexp class is primarily used for the the zoom level and the square of the pixel delta, both of which are positive. Removing the range check should not cause any issues. I've pushed a fix to the development branch.

00ae2b72d2238892aa402fd816de704d7e8145b4
